import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

// 1. Initialize Montserrat
const montserrat = Montserrat({
  subsets: ["latin"],
  // Optional: Specify weights if you don't want the default variable font setup
  // weight: ["400", "500", "600", "700"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      /* 2. Apply font class & CSS variable to html */
      className={`${montserrat.variable} ${montserrat.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
